# Generated by Django 5.0.7 on 2024-07-10 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0003_campeonato_game_final_score1_game_final_score2_bolao'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='campeonato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bolao.campeonato'),
            preserve_default=False,
        ),
    ]
