# Generated by Django 5.0.7 on 2024-07-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0004_game_campeonato'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='fase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
