# Generated by Django 5.0.7 on 2024-07-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0005_game_fase_game_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='final_score1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='final_score2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
